apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bloodsugar-backend
  namespace: bloodsugar
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bloodsugar
      app.kubernetes.io/component: backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bloodsugar-web
  namespace: bloodsugar
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bloodsugar
      app.kubernetes.io/component: web
